In [2]:
import numpy as np # importando a biblioteca de funções do python

In [10]:
# Criar uma matriz unidimensional = array unidimensional
M = np.array([10, 24, 54, 78, 31])
N = np.array([34, 21, 45, 56, 98])

In [5]:
type(M)

numpy.ndarray

In [6]:
print(M)

[10 24 54 78 31]


In [11]:
print("{}".format(M))

[10 24 54 78 31]


In [15]:
print("{}".format(M[2]))

54


In [16]:
# O último elemento de parada [0:4] não entra no cálculo, ele para 1 índice antes
print("{}".format(M[0:4]))


[10 24 54 78]


In [19]:
M

array([10, 24, 54, 78, 31])

In [18]:
print(M.shape)

(5,)


In [20]:
MD = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])

In [21]:
print("{}".format(MD))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
MD.shape

(2, 6)

In [24]:
transp = MD.T # Transpor um array
print(transp)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [25]:
transp.shape

(6, 2)

In [27]:
MD

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [26]:
MD[1,1]

8

In [28]:
MD[1][1]

8

In [29]:
MD.shape[0] # o parâmetro de entrada 0, permite ver a quantidade de linhas do array

2

In [30]:
MD.shape[1] # o parâmetro de entrada 1, permite ver a quantidade de colunas do array

6

In [32]:
MD

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
# Criar uma submatriz

# subMD recebe as linhas localizadas na posição zero e um. E colunas de zero a dois
subMD = MD[0:2, 0:3]

print("{}".format(subMD))

[[1 2 3]
 [7 8 9]]


In [33]:
# Modificar elementos das matrizes
MD[1,1] = 11
print("{}".format(MD))

[[ 1  2  3  4  5  6]
 [ 7 11  9 10 11 12]]


In [37]:
# Transformar para número real
MR = np.array([[1, 2, 3.0, 4, 5], [1000, 12, 32111, 788, 1], [6, 7, 8, 9, 1999]])
# o fato do primeiro elemento ser um float (1.0), que é número real, indica que todos os outros também serão

In [38]:
print("{}".format(MR))

[[1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00 5.0000e+00]
 [1.0000e+03 1.2000e+01 3.2111e+04 7.8800e+02 1.0000e+00]
 [6.0000e+00 7.0000e+00 8.0000e+00 9.0000e+00 1.9990e+03]]


In [36]:
# Matriz identidade

I = np.eye(4)
print("{}".format(I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
